<?php

declare(strict_types=1);

namespace App\JobOffer\Infrastructure\DataFixtures\ORM;

use App\Company\Domain\Entity\Company;
use App\General\Domain\Rest\UuidHelper;
use App\JobOffer\Domain\Entity\City;
use App\JobOffer\Domain\Entity\JobCategory;
use App\JobOffer\Domain\Entity\JobOffer;
use App\JobOffer\Domain\Entity\Language;
use App\JobOffer\Domain\Entity\Region;
use App\JobOffer\Domain\Entity\Skill;
use App\Tests\Utils\PhpUnitUtil;
use App\User\Domain\Entity\User;
use DateTimeImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use Override;

/**
 * @package App\JobOffer
 * @author  Rami Aouinti <rami.aouinti@gmail.com>
 */

final class LoadJobOfferData extends Fixture implements OrderedFixtureInterface
{
    #[Override]
    public function load(ObjectManager $manager): void
    {
        $now = new DateTimeImmutable('now');

        $companies = [
            'acme' => $this->getReference('Company-acme-demo', Company::class),
            'external' => $this->getReference('Company-external-corp', Company::class),
            'beta' => $this->getReference('Company-beta-labs', Company::class),
        ];

        $users = [
            'john' => $this->getReference('User-john-user', User::class),
            'alice' => $this->getReference('User-alice-user', User::class),
            'carol' => $this->getReference('User-carol-user', User::class),
        ];

        $cities = [
            'paris' => $this->getReference('City-paris', City::class),
            'berlin' => $this->getReference('City-berlin', City::class),
            'lyon' => $this->getReference('City-lyon', City::class),
            'toulouse' => $this->getReference('City-toulouse', City::class),
            'barcelona' => $this->getReference('City-barcelona', City::class),
            'madrid' => $this->getReference('City-madrid', City::class),
            'milan' => $this->getReference('City-milan', City::class),
            'amsterdam' => $this->getReference('City-amsterdam', City::class),
            'lisbon' => $this->getReference('City-lisbon', City::class),
            'montreal' => $this->getReference('City-montreal', City::class),
            'sao-paulo' => $this->getReference('City-sao-paulo', City::class),
        ];

        $regions = [
            'idf' => $this->getReference('Region-idf', Region::class),
            'berlin' => $this->getReference('Region-berlin', Region::class),
            'ara' => $this->getReference('Region-ara', Region::class),
            'occitanie' => $this->getReference('Region-occitanie', Region::class),
            'catalonia' => $this->getReference('Region-catalonia', Region::class),
            'madrid' => $this->getReference('Region-madrid', Region::class),
            'lombardy' => $this->getReference('Region-lombardy', Region::class),
            'north-holland' => $this->getReference('Region-north-holland', Region::class),
            'lisbon' => $this->getReference('Region-lisbon', Region::class),
            'quebec' => $this->getReference('Region-quebec', Region::class),
            'sao-paulo' => $this->getReference('Region-sao-paulo', Region::class),
        ];

        $skills = [
            'php' => $this->getReference('Skill-php', Skill::class),
            'symfony' => $this->getReference('Skill-symfony', Skill::class),
            'devops' => $this->getReference('Skill-devops', Skill::class),
            'aws' => $this->getReference('Skill-aws', Skill::class),
            'react' => $this->getReference('Skill-react', Skill::class),
            'sql' => $this->getReference('Skill-sql', Skill::class),
            'git' => $this->getReference('Skill-git', Skill::class),
            'docker' => $this->getReference('Skill-docker', Skill::class),
            'kubernetes' => $this->getReference('Skill-kubernetes', Skill::class),
            'terraform' => $this->getReference('Skill-terraform', Skill::class),
            'postgresql' => $this->getReference('Skill-postgresql', Skill::class),
            'python' => $this->getReference('Skill-python', Skill::class),
            'nodejs' => $this->getReference('Skill-nodejs', Skill::class),
            'typescript' => $this->getReference('Skill-typescript', Skill::class),
            'elasticsearch' => $this->getReference('Skill-elasticsearch', Skill::class),
        ];

        $languages = [
            'fr' => $this->getReference('Language-fr', Language::class),
            'en' => $this->getReference('Language-en', Language::class),
            'de' => $this->getReference('Language-de', Language::class),
            'es' => $this->getReference('Language-es', Language::class),
            'it' => $this->getReference('Language-it', Language::class),
            'pt' => $this->getReference('Language-pt', Language::class),
            'nl' => $this->getReference('Language-nl', Language::class),
        ];

        $categories = [
            'backend' => $this->getReference('JobCategory-backend', JobCategory::class),
            'platform' => $this->getReference('JobCategory-platform', JobCategory::class),
            'data' => $this->getReference('JobCategory-data', JobCategory::class),
            'frontend' => $this->getReference('JobCategory-frontend', JobCategory::class),
            'mobile' => $this->getReference('JobCategory-mobile', JobCategory::class),
            'qa' => $this->getReference('JobCategory-qa', JobCategory::class),
            'product' => $this->getReference('JobCategory-product', JobCategory::class),
        ];

        $jobs = [
            [
                'reference' => 'JobOffer-php-backend-engineer',
                'uuid' => '60000000-0000-1000-8000-000000000001',
                'title' => 'Senior PHP Backend Engineer',
                'description' => 'Design and maintain scalable Symfony services.',
                'location' => 'Paris, France',
                'employmentType' => 'full-time',
                'status' => 'open',
                'company' => $companies['acme'],
                'createdBy' => $users['john'],
                'salaryMin' => 65000,
                'salaryMax' => 85000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'remotePolicy' => 'hybrid',
                'experienceLevel' => 'senior',
                'workTime' => 'full-time',
                'applicationType' => 'internal',
                'publishedAt' => $now->modify('-20 hours'),
                'city' => $cities['paris'],
                'region' => $regions['idf'],
                'jobCategory' => $categories['backend'],
                'skills' => [$skills['php'], $skills['symfony'], $skills['sql'], $skills['git']],
                'languages' => [$languages['fr'], $languages['en']],
                'country' => 'FR',
                'languageLevel' => 'fluent',
            ],
            [
                'reference' => 'JobOffer-platform-sre',
                'uuid' => '60000000-0000-1000-8000-000000000002',
                'title' => 'Platform SRE',
                'description' => 'Improve monitoring, incident response and reliability.',
                'location' => 'Remote EU',
                'employmentType' => 'full-time',
                'status' => 'open',
                'company' => $companies['acme'],
                'createdBy' => $users['alice'],
                'salaryMin' => 70000,
                'salaryMax' => 92000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'remotePolicy' => 'remote',
                'experienceLevel' => 'lead',
                'workTime' => 'full-time',
                'applicationType' => 'external-link',
                'publishedAt' => $now->modify('-2 days'),
                'city' => $cities['berlin'],
                'region' => $regions['berlin'],
                'jobCategory' => $categories['platform'],
                'skills' => [$skills['devops'], $skills['aws'], $skills['kubernetes'], $skills['terraform']],
                'languages' => [$languages['en'], $languages['de']],
                'country' => 'DE',
                'languageLevel' => 'advanced',
            ],
            [
                'reference' => 'JobOffer-data-engineer-external',
                'uuid' => '60000000-0000-1000-8000-000000000003',
                'title' => 'Data Engineer',
                'description' => 'Build ETL pipelines and lakehouse transformations.',
                'location' => 'Lyon, France',
                'employmentType' => 'contract',
                'status' => 'closed',
                'company' => $companies['external'],
                'createdBy' => $users['carol'],
                'salaryMin' => 500,
                'salaryMax' => 700,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'daily',
                'remotePolicy' => 'on-site',
                'experienceLevel' => 'mid',
                'workTime' => 'full-time',
                'applicationType' => 'email',
                'publishedAt' => $now->modify('-31 days'),
                'city' => $cities['lyon'],
                'region' => $regions['ara'],
                'jobCategory' => $categories['data'],
                'skills' => [$skills['sql'], $skills['python'], $skills['git']],
                'languages' => [$languages['fr']],
                'country' => 'FR',
                'languageLevel' => 'intermediate',
            ],
            [
                'reference' => 'JobOffer-junior-frontend-beta',
                'uuid' => '60000000-0000-1000-8000-000000000004',
                'title' => 'Junior Frontend Engineer',
                'description' => 'Help ship UX improvements and tests.',
                'location' => 'Toulouse, France',
                'employmentType' => 'internship',
                'status' => 'draft',
                'company' => $companies['beta'],
                'createdBy' => $users['alice'],
                'salaryMin' => 1200,
                'salaryMax' => 1500,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'monthly',
                'remotePolicy' => 'hybrid',
                'experienceLevel' => 'junior',
                'workTime' => 'part-time',
                'applicationType' => 'internal',
                'publishedAt' => null,
                'city' => $cities['toulouse'],
                'region' => $regions['occitanie'],
                'jobCategory' => $categories['frontend'],
                'skills' => [$skills['react'], $skills['typescript']],
                'languages' => [$languages['fr']],
                'country' => 'FR',
                'languageLevel' => 'basic',
            ],
        ];

        $extraJobs = [
            [
                'slug' => 'staff-backend-paris',
                'title' => 'Staff Backend Engineer',
                'city' => 'paris',
                'region' => 'idf',
                'country' => 'FR',
                'cat' => 'backend',
                'company' => 'acme',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'lead',
                'salaryMin' => 85000,
                'salaryMax' => 110000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['php', 'symfony', 'postgresql', 'git'],
                'published' => '-7 days',
            ],
            [
                'slug' => 'api-architect-berlin',
                'title' => 'API Architect',
                'city' => 'berlin',
                'region' => 'berlin',
                'country' => 'DE',
                'cat' => 'backend',
                'company' => 'external',
                'user' => 'carol',
                'employment' => 'contract',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'senior',
                'salaryMin' => 780,
                'salaryMax' => 980,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'daily',
                'langs' => ['en', 'de'],
                'skills' => ['php', 'symfony', 'sql', 'docker'],
                'published' => '-24 hours',
            ],
            [
                'slug' => 'site-reliability-lyon',
                'title' => 'Site Reliability Engineer',
                'city' => 'lyon',
                'region' => 'ara',
                'country' => 'FR',
                'cat' => 'platform',
                'company' => 'acme',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'on-site',
                'exp' => 'mid',
                'salaryMin' => 58000,
                'salaryMax' => 76000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['devops', 'kubernetes', 'aws', 'git'],
                'published' => '-6 days',
            ],
            [
                'slug' => 'devops-consultant-madrid',
                'title' => 'DevOps Consultant',
                'city' => 'madrid',
                'region' => 'madrid',
                'country' => 'ES',
                'cat' => 'platform',
                'company' => 'external',
                'user' => 'john',
                'employment' => 'freelance',
                'work' => 'part-time',
                'status' => 'closed',
                'remote' => 'hybrid',
                'exp' => 'senior',
                'salaryMin' => 450,
                'salaryMax' => 620,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'daily',
                'langs' => ['es', 'en'],
                'skills' => ['devops', 'terraform', 'docker'],
                'published' => '-30 days',
            ],
            [
                'slug' => 'machine-learning-engineer-montreal',
                'title' => 'Machine Learning Engineer',
                'city' => 'montreal',
                'region' => 'quebec',
                'country' => 'CA',
                'cat' => 'data',
                'company' => 'beta',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'mid',
                'salaryMin' => 90000,
                'salaryMax' => 125000,
                'salaryCurrency' => 'CAD',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['python', 'sql', 'elasticsearch', 'git'],
                'published' => '-3 days',
            ],
            [
                'slug' => 'bi-analyst-milan',
                'title' => 'BI Analyst',
                'city' => 'milan',
                'region' => 'lombardy',
                'country' => 'IT',
                'cat' => 'data',
                'company' => 'external',
                'user' => 'alice',
                'employment' => 'part-time',
                'work' => 'part-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'junior',
                'salaryMin' => 30000,
                'salaryMax' => 38000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['it', 'en'],
                'skills' => ['sql', 'python', 'git'],
                'published' => '-11 days',
            ],
            [
                'slug' => 'frontend-react-madrid',
                'title' => 'Frontend React Engineer',
                'city' => 'madrid',
                'region' => 'madrid',
                'country' => 'ES',
                'cat' => 'frontend',
                'company' => 'acme',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'mid',
                'salaryMin' => 42000,
                'salaryMax' => 58000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['es', 'en'],
                'skills' => ['react', 'typescript', 'git'],
                'published' => '-4 days',
            ],
            [
                'slug' => 'frontend-qa-paris',
                'title' => 'Frontend QA Specialist',
                'city' => 'paris',
                'region' => 'idf',
                'country' => 'FR',
                'cat' => 'qa',
                'company' => 'beta',
                'user' => 'john',
                'employment' => 'contract',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'on-site',
                'exp' => 'mid',
                'salaryMin' => 38000,
                'salaryMax' => 52000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr'],
                'skills' => ['react', 'git', 'sql'],
                'published' => '-9 days',
            ],
            [
                'slug' => 'mobile-engineer-lisbon',
                'title' => 'Mobile Engineer',
                'city' => 'lisbon',
                'region' => 'lisbon',
                'country' => 'PT',
                'cat' => 'mobile',
                'company' => 'acme',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'mid',
                'salaryMin' => 36000,
                'salaryMax' => 49000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['pt', 'en'],
                'skills' => ['nodejs', 'typescript', 'git'],
                'published' => '-2 days',
            ],
            [
                'slug' => 'product-owner-barcelona',
                'title' => 'Technical Product Owner',
                'city' => 'barcelona',
                'region' => 'catalonia',
                'country' => 'ES',
                'cat' => 'product',
                'company' => 'external',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'draft',
                'remote' => 'hybrid',
                'exp' => 'senior',
                'salaryMin' => null,
                'salaryMax' => null,
                'salaryCurrency' => null,
                'salaryPeriod' => null,
                'langs' => ['es', 'en'],
                'skills' => ['git', 'sql'],
                'published' => null,
            ],
            [
                'slug' => 'qa-automation-berlin',
                'title' => 'QA Automation Engineer',
                'city' => 'berlin',
                'region' => 'berlin',
                'country' => 'DE',
                'cat' => 'qa',
                'company' => 'beta',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'mid',
                'salaryMin' => 50000,
                'salaryMax' => 68000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['de', 'en'],
                'skills' => ['python', 'docker', 'git'],
                'published' => '-13 days',
            ],
            [
                'slug' => 'senior-php-lyon',
                'title' => 'Senior PHP Engineer',
                'city' => 'lyon',
                'region' => 'ara',
                'country' => 'FR',
                'cat' => 'backend',
                'company' => 'acme',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'closed',
                'remote' => 'on-site',
                'exp' => 'senior',
                'salaryMin' => 62000,
                'salaryMax' => 78000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['php', 'symfony', 'postgresql', 'git'],
                'published' => '-40 days',
            ],
            [
                'slug' => 'data-platform-paris',
                'title' => 'Data Platform Engineer',
                'city' => 'paris',
                'region' => 'idf',
                'country' => 'FR',
                'cat' => 'data',
                'company' => 'beta',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'senior',
                'salaryMin' => 70000,
                'salaryMax' => 90000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['python', 'sql', 'kubernetes', 'terraform'],
                'published' => '-1 day',
            ],
            [
                'slug' => 'fullstack-amsterdam',
                'title' => 'Fullstack Engineer',
                'city' => 'amsterdam',
                'region' => 'north-holland',
                'country' => 'NL',
                'cat' => 'frontend',
                'company' => 'external',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'mid',
                'salaryMin' => 54000,
                'salaryMax' => 72000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['nl', 'en'],
                'skills' => ['react', 'nodejs', 'typescript', 'git'],
                'published' => '-5 days',
            ],
            [
                'slug' => 'staff-sre-amsterdam',
                'title' => 'Staff SRE',
                'city' => 'amsterdam',
                'region' => 'north-holland',
                'country' => 'NL',
                'cat' => 'platform',
                'company' => 'acme',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'lead',
                'salaryMin' => 95000,
                'salaryMax' => 125000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['en'],
                'skills' => ['devops', 'aws', 'kubernetes', 'terraform', 'git'],
                'published' => '-18 hours',
            ],
            [
                'slug' => 'cloud-engineer-lisbon',
                'title' => 'Cloud Engineer',
                'city' => 'lisbon',
                'region' => 'lisbon',
                'country' => 'PT',
                'cat' => 'platform',
                'company' => 'external',
                'user' => 'carol',
                'employment' => 'contract',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'mid',
                'salaryMin' => 520,
                'salaryMax' => 700,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'daily',
                'langs' => ['pt', 'en'],
                'skills' => ['aws', 'docker', 'terraform'],
                'published' => '-8 days',
            ],
            [
                'slug' => 'junior-data-analyst-toulouse',
                'title' => 'Junior Data Analyst',
                'city' => 'toulouse',
                'region' => 'occitanie',
                'country' => 'FR',
                'cat' => 'data',
                'company' => 'beta',
                'user' => 'john',
                'employment' => 'internship',
                'work' => 'part-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'junior',
                'salaryMin' => 1300,
                'salaryMax' => 1600,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'monthly',
                'langs' => ['fr'],
                'skills' => ['sql', 'python'],
                'published' => '-6 days',
            ],
            [
                'slug' => 'product-analyst-montreal',
                'title' => 'Product Data Analyst',
                'city' => 'montreal',
                'region' => 'quebec',
                'country' => 'CA',
                'cat' => 'product',
                'company' => 'acme',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'mid',
                'salaryMin' => 80000,
                'salaryMax' => 98000,
                'salaryCurrency' => 'CAD',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['sql', 'python', 'git'],
                'published' => '-7 days',
            ],
            [
                'slug' => 'backend-laravel-milan',
                'title' => 'Backend Engineer (PHP)',
                'city' => 'milan',
                'region' => 'lombardy',
                'country' => 'IT',
                'cat' => 'backend',
                'company' => 'external',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'draft',
                'remote' => 'on-site',
                'exp' => 'mid',
                'salaryMin' => 45000,
                'salaryMax' => 60000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['it', 'en'],
                'skills' => ['php', 'sql', 'git'],
                'published' => null,
            ],
            [
                'slug' => 'search-engineer-berlin',
                'title' => 'Search Engineer',
                'city' => 'berlin',
                'region' => 'berlin',
                'country' => 'DE',
                'cat' => 'backend',
                'company' => 'acme',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'senior',
                'salaryMin' => 76000,
                'salaryMax' => 94000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['de', 'en'],
                'skills' => ['php', 'elasticsearch', 'sql', 'git'],
                'published' => '-27 days',
            ],
            [
                'slug' => 'api-support-lisbon',
                'title' => 'API Support Engineer',
                'city' => 'lisbon',
                'region' => 'lisbon',
                'country' => 'PT',
                'cat' => 'backend',
                'company' => 'beta',
                'user' => 'alice',
                'employment' => 'part-time',
                'work' => 'part-time',
                'status' => 'closed',
                'remote' => 'remote',
                'exp' => 'junior',
                'salaryMin' => null,
                'salaryMax' => null,
                'salaryCurrency' => null,
                'salaryPeriod' => null,
                'langs' => ['pt', 'en'],
                'skills' => ['php', 'symfony', 'git'],
                'published' => '-35 days',
            ],
            [
                'slug' => 'principal-platform-paris',
                'title' => 'Principal Platform Engineer',
                'city' => 'paris',
                'region' => 'idf',
                'country' => 'FR',
                'cat' => 'platform',
                'company' => 'acme',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'lead',
                'salaryMin' => 98000,
                'salaryMax' => 130000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['devops', 'aws', 'kubernetes', 'terraform', 'docker'],
                'published' => '-23 hours',
            ],
            [
                'slug' => 'frontend-design-system-barcelona',
                'title' => 'Design System Engineer',
                'city' => 'barcelona',
                'region' => 'catalonia',
                'country' => 'ES',
                'cat' => 'frontend',
                'company' => 'acme',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'mid',
                'salaryMin' => 47000,
                'salaryMax' => 65000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['es', 'en'],
                'skills' => ['react', 'typescript', 'git'],
                'published' => '-12 days',
            ],
            [
                'slug' => 'qa-lead-madrid',
                'title' => 'QA Lead',
                'city' => 'madrid',
                'region' => 'madrid',
                'country' => 'ES',
                'cat' => 'qa',
                'company' => 'external',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'on-site',
                'exp' => 'lead',
                'salaryMin' => 56000,
                'salaryMax' => 73000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['es'],
                'skills' => ['python', 'sql', 'git'],
                'published' => '-29 days',
            ],
            [
                'slug' => 'mobile-android-berlin',
                'title' => 'Android Engineer',
                'city' => 'berlin',
                'region' => 'berlin',
                'country' => 'DE',
                'cat' => 'mobile',
                'company' => 'beta',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'mid',
                'salaryMin' => 62000,
                'salaryMax' => 81000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['de', 'en'],
                'skills' => ['nodejs', 'typescript', 'git'],
                'published' => '-7 days',
            ],
            [
                'slug' => 'product-manager-paris',
                'title' => 'Product Manager (B2B SaaS)',
                'city' => 'paris',
                'region' => 'idf',
                'country' => 'FR',
                'cat' => 'product',
                'company' => 'external',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'senior',
                'salaryMin' => 68000,
                'salaryMax' => 90000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['sql', 'git'],
                'published' => '-15 days',
            ],
            [
                'slug' => 'full-remote-php-brazil-accent',
                'title' => 'PHP Backend Engineer (LATAM)',
                'city' => 'sao-paulo',
                'region' => 'sao-paulo',
                'country' => 'BR',
                'cat' => 'backend',
                'company' => 'acme',
                'user' => 'carol',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'mid',
                'salaryMin' => 120000,
                'salaryMax' => 170000,
                'salaryCurrency' => 'BRL',
                'salaryPeriod' => 'yearly',
                'langs' => ['pt', 'en'],
                'skills' => ['php', 'symfony', 'sql', 'git'],
                'published' => '-16 hours',
            ],
            [
                'slug' => 'full-remote-php-brazil-ascii',
                'title' => 'PHP Backend Engineer (BR Payroll)',
                'city' => 'sao-paulo',
                'location' => 'Sao Paulo, BR',
                'region' => 'sao-paulo',
                'country' => 'BR',
                'cat' => 'backend',
                'company' => 'external',
                'user' => 'alice',
                'employment' => 'contract',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'remote',
                'exp' => 'senior',
                'salaryMin' => 700,
                'salaryMax' => 1000,
                'salaryCurrency' => 'USD',
                'salaryPeriod' => 'daily',
                'langs' => ['pt', 'en'],
                'skills' => ['php', 'symfony', 'docker', 'git'],
                'published' => '-6 days',
            ],
            [
                'slug' => 'bilingual-support-amsterdam',
                'title' => 'Bilingual Support Developer',
                'city' => 'amsterdam',
                'region' => 'north-holland',
                'country' => 'NL',
                'cat' => 'backend',
                'company' => 'beta',
                'user' => 'john',
                'employment' => 'part-time',
                'work' => 'part-time',
                'status' => 'open',
                'remote' => 'on-site',
                'exp' => 'junior',
                'salaryMin' => 2600,
                'salaryMax' => 3400,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'monthly',
                'langs' => ['nl', 'en'],
                'skills' => ['php', 'sql', 'git'],
                'published' => '-10 days',
            ],
            [
                'slug' => 'multi-skill-staff-platform-montreal',
                'title' => 'Staff Platform Engineer (Multi-Cloud)',
                'city' => 'montreal',
                'region' => 'quebec',
                'country' => 'CA',
                'cat' => 'platform',
                'company' => 'acme',
                'user' => 'alice',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'open',
                'remote' => 'hybrid',
                'exp' => 'lead',
                'salaryMin' => 130000,
                'salaryMax' => 165000,
                'salaryCurrency' => 'CAD',
                'salaryPeriod' => 'yearly',
                'langs' => ['fr', 'en'],
                'skills' => ['devops', 'aws', 'kubernetes', 'terraform', 'docker', 'python', 'git'],
                'published' => '-28 days',
            ],
            [
                'slug' => 'draft-intern-data-barcelona',
                'title' => 'Data Internship',
                'city' => 'barcelona',
                'region' => 'catalonia',
                'country' => 'ES',
                'cat' => 'data',
                'company' => 'beta',
                'user' => 'carol',
                'employment' => 'internship',
                'work' => 'part-time',
                'status' => 'draft',
                'remote' => 'hybrid',
                'exp' => 'junior',
                'salaryMin' => 900,
                'salaryMax' => 1100,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'monthly',
                'langs' => ['es', 'en'],
                'skills' => ['python', 'sql'],
                'published' => null,
            ],
            [
                'slug' => 'closed-senior-data-milan',
                'title' => 'Senior Data Engineer',
                'city' => 'milan',
                'region' => 'lombardy',
                'country' => 'IT',
                'cat' => 'data',
                'company' => 'external',
                'user' => 'john',
                'employment' => 'full-time',
                'work' => 'full-time',
                'status' => 'closed',
                'remote' => 'hybrid',
                'exp' => 'senior',
                'salaryMin' => 72000,
                'salaryMax' => 96000,
                'salaryCurrency' => 'EUR',
                'salaryPeriod' => 'yearly',
                'langs' => ['it', 'en'],
                'skills' => ['python', 'sql', 'elasticsearch', 'git'],
                'published' => '-33 days',
            ],
        ];

        foreach ($extraJobs as $index => $seed) {
            $jobs[] = [
                'reference' => 'JobOffer-' . $seed['slug'],
                'uuid' => sprintf('60000000-0000-1000-8000-%012d', $index + 5),
                'title' => $seed['title'],
                'description' => sprintf('%s role with modern engineering practices and delivery ownership.', $seed['title']),
                'location' => $seed['location'] ?? sprintf('%s, %s', $cities[$seed['city']]->getName(), $seed['country']),
                'employmentType' => $seed['employment'],
                'status' => $seed['status'],
                'company' => $companies[$seed['company']],
                'createdBy' => $users[$seed['user']],
                'salaryMin' => $seed['salaryMin'],
                'salaryMax' => $seed['salaryMax'],
                'salaryCurrency' => $seed['salaryCurrency'],
                'salaryPeriod' => $seed['salaryPeriod'],
                'remotePolicy' => $seed['remote'],
                'experienceLevel' => $seed['exp'],
                'workTime' => $seed['work'],
                'applicationType' => $seed['status'] === 'open' ? 'external-link' : 'internal',
                'publishedAt' => $seed['published'] === null ? null : $now->modify($seed['published']),
                'city' => $cities[$seed['city']],
                'region' => $regions[$seed['region']],
                'jobCategory' => $categories[$seed['cat']],
                'skills' => array_map(static fn (string $skill): Skill => $skills[$skill], $seed['skills']),
                'languages' => array_map(static fn (string $language): Language => $languages[$language], $seed['langs']),
                'country' => $seed['country'],
                'languageLevel' => count($seed['langs']) >= 2 ? 'advanced' : 'intermediate',
            ];
        }

        foreach ($jobs as $data) {
            $job = (new JobOffer())
                ->setTitle($data['title'])
                ->setDescription($data['description'])
                ->setLocation($data['location'])
                ->setEmploymentType($data['employmentType'])
                ->setStatus($data['status'])
                ->setCompany($data['company'])
                ->setCreatedBy($data['createdBy'])
                ->setSalaryMin($data['salaryMin'])
                ->setSalaryMax($data['salaryMax'])
                ->setSalaryCurrency($data['salaryCurrency'])
                ->setSalaryPeriod($data['salaryPeriod'])
                ->setRemotePolicy($data['remotePolicy'])
                ->setExperienceLevel($data['experienceLevel'])
                ->setWorkTime($data['workTime'])
                ->setApplicationType($data['applicationType'])
                ->setPublishedAt($data['publishedAt'])
                ->setCity($data['city'])
                ->setRegion($data['region'])
                ->setJobCategory($data['jobCategory'])
                ->setCountry($data['country'])
                ->setLanguageLevel($data['languageLevel'])
                ->setSkills($data['skills'])
                ->setLanguages($data['languages']);

            PhpUnitUtil::setProperty('id', UuidHelper::fromString($data['uuid']), $job);
            $manager->persist($job);
            $this->addReference($data['reference'], $job);
        }

        $manager->flush();
    }

    #[Override]
    public function getOrder(): int
    {
        return 6;
    }
}
